services:
  - type: web
    name: shopify-lead-agent
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: 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
        sync: false
      - key: https://script.google.com/macros/s/AKfycbxyPB4XQx5mX63qQMBJHjbDlk3vBChoSW06Bkp0bDT9kFHCxAQPouD2RXULWizqLXi2xw/exec
        sync: false
